export const countryMapping: Record<string, { cn: string; en: string }> = {
  "004": { cn: "阿富汗", en: "Afghanistan" },
  "008": { cn: "阿尔巴尼亚", en: "Albania" },
  "012": { cn: "阿尔及利亚", en: "Algeria" },
  "016": { cn: "美属萨摩亚", en: "American Samoa" },
  "020": { cn: "安道尔", en: "Andorra" },
  "024": { cn: "安哥拉", en: "Angola" },
  "028": { cn: "安提瓜和巴布达", en: "Antigua and Barbuda" },
  "031": { cn: "阿塞拜疆", en: "Azerbaijan" },
  "032": { cn: "阿根廷", en: "Argentina" },
  "036": { cn: "澳大利亚", en: "Australia" },
  "040": { cn: "奥地利", en: "Austria" },
  "044": { cn: "巴哈马", en: "Bahamas" },
  "048": { cn: "巴林", en: "Bahrain" },
  "050": { cn: "孟加拉国", en: "Bangladesh" },
  "051": { cn: "亚美尼亚", en: "Armenia" },
  "052": { cn: "巴巴多斯", en: "Barbados" },
  "056": { cn: "比利时", en: "Belgium" },
  "060": { cn: "百慕大", en: "Bermuda" },
  "064": { cn: "不丹", en: "Bhutan" },
  "068": { cn: "玻利维亚", en: "Bolivia" },
  "070": { cn: "波黑", en: "Bosnia and Herz." },
  "072": { cn: "博茨瓦纳", en: "Botswana" },
  "076": { cn: "巴西", en: "Brazil" },
  "084": { cn: "伯利兹", en: "Belize" },
  "090": { cn: "所罗门群岛", en: "Solomon Is." },
  "092": { cn: "英属维尔京群岛", en: "British Virgin Is." },
  "096": { cn: "文莱", en: "Brunei" },
  "100": { cn: "保加利亚", en: "Bulgaria" },
  "104": { cn: "缅甸", en: "Myanmar" },
  "108": { cn: "布隆迪", en: "Burundi" },
  "112": { cn: "白俄罗斯", en: "Belarus" },
  "116": { cn: "柬埔寨", en: "Cambodia" },
  "120": { cn: "喀麦隆", en: "Cameroon" },
  "124": { cn: "加拿大", en: "Canada" },
  "132": { cn: "佛得角", en: "Cape Verde" },
  "136": { cn: "开曼群岛", en: "Cayman Is." },
  "140": { cn: "中非", en: "Central African Rep." },
  "144": { cn: "斯里兰卡", en: "Sri Lanka" },
  "148": { cn: "乍得", en: "Chad" },
  "152": { cn: "智利", en: "Chile" },
  "156": { cn: "中国", en: "China" },
  "158": { cn: "中国台湾", en: "Taiwan" },
  "170": { cn: "哥伦比亚", en: "Colombia" },
  "174": { cn: "科摩罗", en: "Comoros" },
  "175": { cn: "马约特", en: "Mayotte" },
  "178": { cn: "刚果（布）", en: "Congo" },
  "180": { cn: "刚果（金）", en: "Dem. Rep. Congo" },
  "184": { cn: "库克群岛", en: "Cook Is." },
  "188": { cn: "哥斯达黎加", en: "Costa Rica" },
  "191": { cn: "克罗地亚", en: "Croatia" },
  "192": { cn: "古巴", en: "Cuba" },
  "196": { cn: "塞浦路斯", en: "Cyprus" },
  "203": { cn: "捷克", en: "Czech Rep." },
  "204": { cn: "贝宁", en: "Benin" },
  "208": { cn: "丹麦", en: "Denmark" },
  "212": { cn: "多米尼克", en: "Dominica" },
  "214": { cn: "多米尼加", en: "Dominican Rep." },
  "218": { cn: "厄瓜多尔", en: "Ecuador" },
  "222": { cn: "萨尔瓦多", en: "El Salvador" },
  "226": { cn: "赤道几内亚", en: "Eq. Guinea" },
  "231": { cn: "埃塞俄比亚", en: "Ethiopia" },
  "232": { cn: "厄立特里亚", en: "Eritrea" },
  "233": { cn: "爱沙尼亚", en: "Estonia" },
  "234": { cn: "法罗群岛", en: "Faeroe Is." },
  "238": { cn: "福克兰群岛", en: "Falkland Is." },
  "242": { cn: "斐济", en: "Fiji" },
  "246": { cn: "芬兰", en: "Finland" },
  "250": { cn: "法国", en: "France" },
  "254": { cn: "法属圭亚那", en: "French Guiana" },
  "258": { cn: "法属波利尼西亚", en: "French Polynesia" },
  "262": { cn: "吉布提", en: "Djibouti" },
  "266": { cn: "加蓬", en: "Gabon" },
  "268": { cn: "格鲁吉亚", en: "Georgia" },
  "270": { cn: "冈比亚", en: "Gambia" },
  "276": { cn: "德国", en: "Germany" },
  "288": { cn: "加纳", en: "Ghana" },
  "292": { cn: "直布罗陀", en: "Gibraltar" },
  "296": { cn: "基里巴斯", en: "Kiribati" },
  "300": { cn: "希腊", en: "Greece" },
  "304": { cn: "格陵兰", en: "Greenland" },
  "308": { cn: "格林纳达", en: "Grenada" },
  "312": { cn: "瓜德罗普", en: "Guadeloupe" },
  "316": { cn: "关岛", en: "Guam" },
  "320": { cn: "危地马拉", en: "Guatemala" },
  "324": { cn: "几内亚", en: "Guinea" },
  "328": { cn: "圭亚那", en: "Guyana" },
  "332": { cn: "海地", en: "Haiti" },
  "336": { cn: "梵蒂冈", en: "Vatican City" },
  "340": { cn: "洪都拉斯", en: "Honduras" },
  "344": { cn: "中国香港", en: "Hong Kong" },
  "348": { cn: "匈牙利", en: "Hungary" },
  "352": { cn: "冰岛", en: "Iceland" },
  "356": { cn: "印度", en: "India" },
  "360": { cn: "印度尼西亚", en: "Indonesia" },
  "364": { cn: "伊朗", en: "Iran" },
  "368": { cn: "伊拉克", en: "Iraq" },
  "372": { cn: "爱尔兰", en: "Ireland" },
  "376": { cn: "以色列", en: "Israel" },
  "380": { cn: "意大利", en: "Italy" },
  "384": { cn: "科特迪瓦", en: "Côte d'Ivoire" },
  "388": { cn: "牙买加", en: "Jamaica" },
  "392": { cn: "日本", en: "Japan" },
  "398": { cn: "哈萨克斯坦", en: "Kazakhstan" },
  "400": { cn: "约旦", en: "Jordan" },
  "404": { cn: "肯尼亚", en: "Kenya" },
  "408": { cn: "朝鲜", en: "North Korea" },
  "410": { cn: "韩国", en: "South Korea" },
  "414": { cn: "科威特", en: "Kuwait" },
  "417": { cn: "吉尔吉斯斯坦", en: "Kyrgyzstan" },
  "418": { cn: "老挝", en: "Laos" },
  "422": { cn: "黎巴嫩", en: "Lebanon" },
  "426": { cn: "莱索托", en: "Lesotho" },
  "428": { cn: "拉脱维亚", en: "Latvia" },
  "430": { cn: "利比里亚", en: "Liberia" },
  "434": { cn: "利比亚", en: "Libya" },
  "438": { cn: "列支敦士登", en: "Liechtenstein" },
  "440": { cn: "立陶宛", en: "Lithuania" },
  "442": { cn: "卢森堡", en: "Luxembourg" },
  "446": { cn: "中国澳门", en: "Macao" },
  "450": { cn: "马达加斯加", en: "Madagascar" },
  "454": { cn: "马拉维", en: "Malawi" },
  "458": { cn: "马来西亚", en: "Malaysia" },
  "462": { cn: "马尔代夫", en: "Maldives" },
  "466": { cn: "马里", en: "Mali" },
  "470": { cn: "马耳他", en: "Malta" },
  "474": { cn: "马提尼克", en: "Martinique" },
  "478": { cn: "毛里塔尼亚", en: "Mauritania" },
  "480": { cn: "毛里求斯", en: "Mauritius" },
  "484": { cn: "墨西哥", en: "Mexico" },
  "492": { cn: "摩纳哥", en: "Monaco" },
  "496": { cn: "蒙古", en: "Mongolia" },
  "498": { cn: "摩尔多瓦", en: "Moldova" },
  "499": { cn: "黑山", en: "Montenegro" },
  "504": { cn: "摩洛哥", en: "Morocco" },
  "508": { cn: "莫桑比克", en: "Mozambique" },
  "512": { cn: "阿曼", en: "Oman" },
  "516": { cn: "纳米比亚", en: "Namibia" },
  "520": { cn: "瑙鲁", en: "Nauru" },
  "524": { cn: "尼泊尔", en: "Nepal" },
  "528": { cn: "荷兰", en: "Netherlands" },
  "531": { cn: "库拉索", en: "Curaçao" },
  "533": { cn: "阿鲁巴", en: "Aruba" },
  "540": { cn: "新喀里多尼亚", en: "New Caledonia" },
  "548": { cn: "瓦努阿图", en: "Vanuatu" },
  "554": { cn: "新西兰", en: "New Zealand" },
  "558": { cn: "尼加拉瓜", en: "Nicaragua" },
  "562": { cn: "尼日尔", en: "Niger" },
  "566": { cn: "尼日利亚", en: "Nigeria" },
  "570": { cn: "纽埃", en: "Niue" },
  "578": { cn: "挪威", en: "Norway" },
  "583": { cn: "密克罗尼西亚", en: "Micronesia" },
  "584": { cn: "马绍尔群岛", en: "Marshall Is." },
  "585": { cn: "帕劳", en: "Palau" },
  "586": { cn: "巴基斯坦", en: "Pakistan" },
  "591": { cn: "巴拿马", en: "Panama" },
  "598": { cn: "巴布亚新几内亚", en: "Papua New Guinea" },
  "600": { cn: "巴拉圭", en: "Paraguay" },
  "604": { cn: "秘鲁", en: "Peru" },
  "608": { cn: "菲律宾", en: "Philippines" },
  "612": { cn: "皮特凯恩群岛", en: "Pitcairn Is." },
  "616": { cn: "波兰", en: "Poland" },
  "620": { cn: "葡萄牙", en: "Portugal" },
  "624": { cn: "几内亚比绍", en: "Guinea-Bissau" },
  "626": { cn: "东帝汶", en: "Timor-Leste" },
  "630": { cn: "波多黎各", en: "Puerto Rico" },
  "634": { cn: "卡塔尔", en: "Qatar" },
  "638": { cn: "留尼汪", en: "Réunion" },
  "642": { cn: "罗马尼亚", en: "Romania" },
  "643": { cn: "俄罗斯", en: "Russia" },
  "646": { cn: "卢旺达", en: "Rwanda" },
  "659": { cn: "圣基茨和尼维斯", en: "St. Kitts and Nevis" },
  "662": { cn: "圣卢西亚", en: "St. Lucia" },
  "666": { cn: "圣皮埃尔和密克隆", en: "St. Pierre and Miquelon" },
  "670": { cn: "圣文森特和格林纳丁斯", en: "St. Vincent and Grenadines" },
  "674": { cn: "圣马力诺", en: "San Marino" },
  "678": { cn: "圣多美和普林西比", en: "São Tomé and Principe" },
  "682": { cn: "沙特阿拉伯", en: "Saudi Arabia" },
  "686": { cn: "塞内加尔", en: "Senegal" },
  "688": { cn: "塞尔维亚", en: "Serbia" },
  "690": { cn: "塞舌尔", en: "Seychelles" },
  "694": { cn: "塞拉利昂", en: "Sierra Leone" },
  "702": { cn: "新加坡", en: "Singapore" },
  "703": { cn: "斯洛伐克", en: "Slovakia" },
  "704": { cn: "越南", en: "Vietnam" },
  "705": { cn: "斯洛文尼亚", en: "Slovenia" },
  "706": { cn: "索马里", en: "Somalia" },
  "710": { cn: "南非", en: "South Africa" },
  "716": { cn: "津巴布韦", en: "Zimbabwe" },
  "724": { cn: "西班牙", en: "Spain" },
  "728": { cn: "南苏丹", en: "South Sudan" },
  "729": { cn: "苏丹", en: "Sudan" },
  "732": { cn: "西撒哈拉", en: "W. Sahara" },
  "740": { cn: "苏里南", en: "Suriname" },
  "744": { cn: "斯瓦尔巴和扬马延", en: "Svalbard and Jan Mayen" },
  "748": { cn: "斯威士兰", en: "Swaziland" },
  "752": { cn: "瑞典", en: "Sweden" },
  "756": { cn: "瑞士", en: "Switzerland" },
  "760": { cn: "叙利亚", en: "Syria" },
  "762": { cn: "塔吉克斯坦", en: "Tajikistan" },
  "764": { cn: "泰国", en: "Thailand" },
  "768": { cn: "多哥", en: "Togo" },
  "772": { cn: "托克劳", en: "Tokelau" },
  "776": { cn: "汤加", en: "Tonga" },
  "780": { cn: "特立尼达和多巴哥", en: "Trinidad and Tobago" },
  "784": { cn: "阿联酋", en: "United Arab Emirates" },
  "788": { cn: "突尼斯", en: "Tunisia" },
  "792": { cn: "土耳其", en: "Turkey" },
  "795": { cn: "土库曼斯坦", en: "Turkmenistan" },
  "796": { cn: "特克斯和凯科斯群岛", en: "Turks and Caicos Is." },
  "798": { cn: "图瓦卢", en: "Tuvalu" },
  "800": { cn: "乌干达", en: "Uganda" },
  "804": { cn: "乌克兰", en: "Ukraine" },
  "807": { cn: "北马其顿", en: "North Macedonia" },
  "818": { cn: "埃及", en: "Egypt" },
  "826": { cn: "英国", en: "United Kingdom" },
  "834": { cn: "坦桑尼亚", en: "Tanzania" },
  "840": { cn: "美国", en: "United States" },
  "850": { cn: "美属维尔京群岛", en: "U.S. Virgin Is." },
  "854": { cn: "布基纳法索", en: "Burkina Faso" },
  "858": { cn: "乌拉圭", en: "Uruguay" },
  "860": { cn: "乌兹别克斯坦", en: "Uzbekistan" },
  "862": { cn: "委内瑞拉", en: "Venezuela" },
  "876": { cn: "瓦利斯和富图纳", en: "Wallis and Futuna" },
  "882": { cn: "萨摩亚", en: "Samoa" },
  "887": { cn: "也门", en: "Yemen" },
  "894": { cn: "赞比亚", en: "Zambia" },
  "000": { cn: "未知", en: "Unknown" },
  "010": { cn: "南极洲", en: "Antarctica" },
  "248": { cn: "奥兰群岛", en: "Åland Islands" },
  "260": { cn: "法属南部领地", en: "French Southern Territories" },
  "334": { cn: "赫德岛和麦克唐纳群岛", en: "Heard Island and McDonald Islands" },
  "574": { cn: "诺福克岛", en: "Norfolk Island" },
  "652": { cn: "圣巴泰勒米", en: "Saint Barthélemy" },
  "663": { cn: "法属圣马丁", en: "Saint Martin (French part)" },
  "736": { cn: "苏丹", en: "Sudan" },
  "830": { cn: "海峡群岛", en: "Channel Islands" },
  "831": { cn: "根西岛", en: "Guernsey" },
  "832": { cn: "泽西岛", en: "Jersey" },
  "833": { cn: "马恩岛", en: "Isle of Man" },
};

export const getCountryName = (idOrName: string) => {
  const mapping = countryMapping[idOrName];
  if (mapping) {
    return `${mapping.cn} (${mapping.en})`;
  }
  return idOrName;
};
